language: python

python:
  - "2.7"

branches:
  only:
    - master

addons:
  postgresql: "9.3"

services:
    - postgres
    - mysql

# Note: conda is not available for anything but python 2.7. So below we try to install
# conda in 2.7 and use conda to install dependencies in the virtualenv for version x.y
install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

  # Install dependencies
  - conda create -n test-environment python=$TRAVIS_PYTHON_VERSION pytest numpy sqlalchemy pandas pip
  - source activate test-environment
  - conda install -c https://conda.binstar.org/chuongdo mysql-python
  - conda install -c https://conda.binstar.org/chuongdo psycopg2

  # Install MongoDB
  - pip install pymongo

#nothing to do before hand postgres db already exists
#before_script:

script: py.test --doctest-modules --verbose --pyargs
